# PLEASE SEE README.md FOR MORE INFO

version: '3'

services:
  php:
    container_name: php
    build: .
    volumes:
      - ./data:/var/www
      - ./logs:/var/log/nginx

  nginx:
    container_name: nginx
    image: nginx
    restart: always
    volumes:
      - ./default.conf.template:/etc/nginx/templates/default.conf.template
    ports:
      - 80:80
    depends_on:
      - php

  db:
    container_name: db
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: test
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./database:/var/lib/mysql

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_HOST=db
      - PMA_USER=user
      - PMA_PASSWORD=password
    depends_on:
      - db
